### ISSUE TITLE
Get releases `v0.5.0` and `v1.0.0-M1` done

### ISSUE THREAD

**Issue by danicheg** [http4s/http4s-armeria#226]
Hi, @ikhoon. I've prepared drafts for two releases [`v0.5.0`](https://github.com/http4s/http4s-armeria/releases/tag/untagged-ae8cfd6b027f9d941efe) and [`v1.0.0-M1`](https://github.com/http4s/http4s-armeria/releases/tag/untagged-18965a2bfbcc02ba2d4c). If you want you can add/change anything there, or we can publish them one by one. 🙇🏻‍♂️

**Comment by ikhoon** [comment]
I have nothing to add. Please go ahead and publish them. 🙇‍♂️

**Comment by danicheg** [comment]
Here we go [v0.5.0](https://github.com/http4s/http4s-armeria/releases/tag/v0.5.0) [v1.0.0-M1](https://github.com/http4s/http4s-armeria/releases/tag/v1.0.0-M1)
