### ISSUE TITLE
The lack of ability to change the default service error handling

### ISSUE THREAD

**Issue by danicheg** [http4s/http4s-armeria#574]
While investigating #573, I've found that `ArmeriaServerBuilder#serviceErrorHandler` is unused resulting in the lack of ability to change the default service error handler `org.http4s.server.package$#DefaultServiceErrorHandler`.

**Comment by ikhoon** [comment]
It was my mistake. 😅 `ArmeriaHttp4sHandler` should be fixed to use `ArmeriaServerBuilder#serviceErrorHandler`.

**Comment by danicheg** [comment]
Yeah, the fix is quite straightforward. I'll drop a PR this weekend. But your review is highly appreciated! :)
